version: '3.7'
services:
  openldap:
    build:
      dockerfile: Dockerfile-openldap
      context: .
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "techinterview.com"
      LDAP_ADMIN_PASSWORD: "123456"
    ports:
      - "389:389"
  ldap-api:
    build: .
    container_name: ldap-api
    ports:
      - "8080:8080"
    depends_on:
      - openldap